// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFulq1NCYQbX1TkUFlbDidmgB6zrGe18U',
    appId: '1:194883924746:android:33e6e0f04a848a192dc0f3',
    messagingSenderId: '194883924746',
    projectId: 'nursewayapp',
    storageBucket: 'nursewayapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl5X6-rziNzen6fMrksaG3MFj0G_sj5gM',
    appId: '1:194883924746:ios:b0c165d7e56071ec2dc0f3',
    messagingSenderId: '194883924746',
    projectId: 'nursewayapp',
    storageBucket: 'nursewayapp.appspot.com',
    androidClientId: '194883924746-rtur04s2mhhb5q8pa5ntbqiovbg49fjn.apps.googleusercontent.com',
    iosClientId: '194883924746-vtn00v0al2odvu5dia9g4jootgvbkg8a.apps.googleusercontent.com',
    iosBundleId: 'com.otmhvecu.nursewayApp',
  );

}